better scripts

diff --git a/scripts/chroot/gb-update-chroot b/scripts/chroot/gb-update-chroot
--- a/scripts/chroot/gb-update-chroot
+++ b/scripts/chroot/gb-update-chroot
@@ -8,14 +8,26 @@ then
     source /etc/init.d/functions.sh
 fi
 
-ebegin "emerge update"
-emerge --keep-going=y --update --deep --changed-use --with-bdeps=y @world
-eend $? "Update failed"
+check_exit()
+{
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]
+    then
+        if [ $1 -ne 0 ]
+        then
+            eerror "$2 failed"
+            exit $RETVAL
+        else
+            ewarn "$2 failed"
+        fi
+    fi
+}
 
-ebegin "emerge depclean"
+emerge --verbose --keep-going=y --update --deep --changed-use --with-bdeps=y @world
+check_exit 1 "Update"
+
 emerge --depclean
-eend $? "Depclean failed"
+check_exit 0 "Depclean"
 
-ebegin "eclean packages"
 eclean packages
-eend $? "Clean packages failed"
+check_exit 0 "Clean packages"
diff --git a/scripts/host/gb-update-host b/scripts/host/gb-update-host
--- a/scripts/host/gb-update-host
+++ b/scripts/host/gb-update-host
@@ -8,24 +8,35 @@ then
     source /etc/init.d/functions.sh
 fi
 
+check_exit()
+{
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]
+    then
+        if [ $1 -ne 0 ]
+        then
+            eerror "$2 failed"
+            exit $RETVAL
+        else
+            ewarn "$2 failed"
+        fi
+    fi
+}
+
 rc-service rsyncd stop
 
-ebegin "emerge --sync"
-emerge --sync > /dev/null
-eend $? "Sync failed"
+emerge --sync
+check_exit 1 "Sync"
 
-ebegin "emerge update"
-emerge --keep-going=y --update --deep --changed-use --with-bdeps=y @world
-eend $? "Host update failed"
+emerge --verbose --keep-going=y --update --deep --changed-use --with-bdeps=y @world
+check_exit 1 "Host update"
 
-ebegin "emerge depclean"
 emerge --depclean --exclude="sys-kernel/linux-image"
-eend $? "Host depclean failed"
+check_exit 0 "Host depclean"
 
 gb-all gb-update-chroot
 
-ebegin "eclean distfiles"
 eclean distfiles
-eend $? "Host distfiles failed"
+check_exit 0 "Host distfiles"
 
 rc-service rsyncd start
diff --git a/scripts/target/gb-update-target b/scripts/target/gb-update-target
--- a/scripts/target/gb-update-target
+++ b/scripts/target/gb-update-target
@@ -8,22 +8,32 @@ then
     source /etc/init.d/functions.sh
 fi
 
-ebegin "emerge --sync"
-emerge --sync > /dev/null
-eend $? "Sync failed"
+check_exit()
+{
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]
+    then
+        if [ $1 -ne 0 ]
+        then
+            eerror "$2 failed"
+            exit $RETVAL
+        else
+            ewarn "$2 failed"
+        fi
+    fi
+}
 
-ebegin "emerge update"
-emerge --keep-going=y --update --deep --changed-use --binpkg-changed-deps=y @world
-eend $? "Update failed"
+emerge --sync
+check_exit 1 "Sync"
 
-ebegin "emerge depclean"
+emerge --verbose --keep-going=y --update --deep --changed-use @world
+check_exit 1 "Update"
+
 emerge --depclean --with-bdeps=n --exclude="sys-kernel/linux-image"
-eend $? "Depclean failed"
+check_exit 0 "Depclean"
 
-ebegin "eclean packages"
 eclean --deep packages
-eend $? "Clean packages failed"
+check_exit 0 "Clean packages"
 
-ebegin "eclean distfiles"
 eclean --deep distfiles
-eend $? "Clean distfiles failed"
+check_exit 0 "Clean distfiles"
