check exit codes

diff --git a/scripts/host/gb-all b/scripts/host/gb-all
--- a/scripts/host/gb-all
+++ b/scripts/host/gb-all
@@ -10,7 +10,18 @@ fi
 
 source /etc/conf.d/gb-chroot
 
+EXIT_CODE=0
+
 for i in $UPDATE_CHROOT
 do
     gb-enter "$i" "${@:1}"
+
+    RETVAL=$?
+    if [ $RETVAL -ne 0 ]
+        then
+            eerror "$i failed"
+            EXIT_CODE=$RETVAL
+    fi    
 done
+
+exit $EXIT_CODE
diff --git a/scripts/host/gb-update-host b/scripts/host/gb-update-host
--- a/scripts/host/gb-update-host
+++ b/scripts/host/gb-update-host
@@ -40,8 +40,14 @@ emerge --depclean --exclude="sys-kernel/linux-image"
 check_exit 0 "Host depclean"
 
 gb-all gb-update-chroot
+ALL_RETVAL=$?
 
 eclean distfiles
 check_exit 0 "Host distfiles"
 
-rc-service rsyncd start
+if [ $ALL_RETVAL -ne 0 ]
+    then
+        eerror "gb-all failed, not starting rsyncd"
+    else
+        rc-service rsyncd start
+fi
